steps:
  # Build the container image for staging
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/holiday-park-api-staging:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/holiday-park-api-staging:latest'
      - '-f'
      - 'apps/api/Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/holiday-park-api-staging:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/holiday-park-api-staging:latest'

  # Deploy container image to Cloud Run (staging)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'holiday-park-api-staging'
      - '--image'
      - 'gcr.io/$PROJECT_ID/holiday-park-api-staging:$COMMIT_SHA'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--service-account'
      - 'holiday-park-api@ai-lab-1-451411.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NODE_ENV=staging,FIREBASE_PROJECT_ID=ai-lab-1-451411'
      - '--update-secrets'
      - 'JWT_SECRET=jwt-secret:latest,SCHEDULER_TOKEN=scheduler-token:latest'

images:
  - 'gcr.io/$PROJECT_ID/holiday-park-api-staging:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/holiday-park-api-staging:latest'

options:
  logging: CLOUD_LOGGING_ONLY